name = "abad-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[site]
bucket = "dist"
entry-point = "."

[env.production]
workers_dev = true 